version: '3.3'

services:
  mobileDataUsage:
    image: wareagledocker/mobileDataUsage:latest
    environment:
      - CONFIG_FILE:/project/config.json
    volumes:
      - ../src/main/resources/private_config.json:/project/config.json:ro
    restart: unless-stopped
